I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 24, in script
    scene bg conves with dissolve
TypeError: __init__() got multiple values for argument 'old_widget'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 24, in script
    scene bg conves with dissolve
  File "/Volumes/renpy-8.2.1-sdk/renpy-8.2.1-sdk/renpy/ast.py", line 1363, in execute
    renpy.exports.with_statement(trans, paired=paired)
  File "/Volumes/renpy-8.2.1-sdk/renpy-8.2.1-sdk/renpy/exports.py", line 1781, in with_statement
    return renpy.game.interface.do_with(trans, paired, clear=clear)
  File "/Volumes/renpy-8.2.1-sdk/renpy-8.2.1-sdk/renpy/display/core.py", line 1548, in do_with
    return self.interact(trans_pause=True,
  File "/Volumes/renpy-8.2.1-sdk/renpy-8.2.1-sdk/renpy/display/core.py", line 2165, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "/Volumes/renpy-8.2.1-sdk/renpy-8.2.1-sdk/renpy/display/core.py", line 2608, in interact_core
    trans = instantiate_transition(None, old_root, layers_root)
  File "/Volumes/renpy-8.2.1-sdk/renpy-8.2.1-sdk/renpy/display/core.py", line 2518, in instantiate_transition
    trans = self.ongoing_transition[layer](
TypeError: __init__() got multiple values for argument 'old_widget'

macOS-14.5-arm64-arm-64bit arm64
Ren'Py 8.2.1.24030407
projeto_X 1.0
Mon Jun 24 13:51:03 2024
